pipeline {
    agent any
    tools {
        maven 'Maven'
        jdk 'JDK'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH=${PATH}"
                    echo "M2_HOME=${M2_HOME}"
                '''
            }
        }
        stage ('Git Checkout') {
            steps {
                git url: 'https://github.com/muthu-s/ProjectJenkins.git', branch: 'feature1'
            }
        }
        stage ('Build') {
            steps {
                dir ('/var/lib/jenkins/workspace/pipeline/payslip') {
                    sh 'mvn clean verify -Dtest=VariableComponentTest -DskipITs=true javadoc:javadoc'
                }
            }
        }
    }
}
